Repository tini-transcendence/tini-pong, pull requests merged in 2024-03, with the labels that each got.

#4 42 OAuth 적용
  server/.gitignore
  server/Pipfile
  server/Pipfile.lock
  server/server/__pycache__/__init__.cpython-39.pyc
  server/server/__pycache__/settings.cpython-39.pyc
  server/server/settings.py
  server/server/urls.py
  server/user/__init__.py
  server/user/admin.py
  server/user/apps.py
  server/user/migrations/__init__.py
  server/user/models.py
  server/user/tests.py
  server/user/urls.py
  server/user/views.py
  server/util/__init__.py
  server/util/jwt.py
Labels: backend, feature

#6 Frontend 라우팅 및 기본 페이지 구성
  .DS_Store
  .gitignore
  frontend/.vscode/settings.json
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/AbstractComponent.js
  frontend/src/components/Lobby.js
  frontend/src/components/Login.js
  frontend/src/components/Main.js
  frontend/src/components/MyPage.js
  frontend/src/components/Navbar.js
  frontend/src/components/NotFound.js
  frontend/src/components/Users.js
  frontend/src/index.js
  frontend/src/style.css
Labels: frontend, feature

#5 JWT 패키지 구현
  server/user/views.py
  server/util/jwt.py
  server/util/timestamp.py
Labels: backend, feature

#14 FrontEnd 페이지 구성
  frontend/src/components/Lobby.js
  frontend/src/components/MyPage.js
  frontend/src/components/Navbar.js
  frontend/src/components/UserEdit.js
  frontend/src/img/default_profile.png
  frontend/src/index.js
Labels: frontend, feature

#11 로그인 기능 구현
  server/user/migrations/0002_alter_user_id_42.py
  server/user/models.py
  server/user/views.py
Labels: backend, feature

#16 CORS 해결
  server/Pipfile
  server/Pipfile.lock
  server/server/settings.py
Labels: backend, feature

#17 CORS origin 추가
  server/server/settings.py
Labels: backend, fix

#20 유저 로그인 수정 및 개선
  server/user/views.py
Labels: backend, feature, fix

#21 Lobby Page 방 목록 및 생성 db와 연동
  frontend/src/components/Lobby.js
  server/room/views.py
Labels: frontend, feature

#23 FrontEnd Login token 발급 기능
  frontend/src/components/Login.js
  frontend/src/components/Oauth.js
  frontend/src/index.js
Labels: frontend, feature

#24 JWT 인증 미들웨어 작성
  server/middleware/__init__.py
  server/middleware/auth_middleware.py
  server/server/settings.py
  server/user/views.py
  server/util/jwt.py
Labels: backend, feature

#26 401 응답을 반환하는 API 추가
  server/auth/__init__.py
  server/auth/apps.py
  server/auth/urls.py
  server/auth/views.py
  server/server/settings.py
  server/server/urls.py
Labels: backend, feature

#28 Refresh Token을 통한 Access Token 발급 API
  server/auth/migrations/0001_initial.py
  server/auth/migrations/__init__.py
  server/auth/models.py
  server/auth/urls.py
  server/auth/views.py
  server/user/views.py
Labels: backend, feature

#31 :sparkles: chore: redis 필요 없대서 내립니다
  docker-compose.yml
  server/server/settings.py
Labels: chore

#30 local pong game 추가
  frontend/index.html
  frontend/src/components/Local.js
  frontend/src/games/local_pong.js
  frontend/src/index.js
Labels: frontend, feature

#32 LoginModule 수정
  frontend/src/components/Main.js
  frontend/src/components/Oauth.js
  frontend/src/utils/fetchmodule.js
  frontend/src/utils/loginmodule.js
Labels: frontend, fix

#33 로그인 인증 시 오류 수정
  server/auth/views.py
  server/server/settings.py
  server/user/views.py
Labels: backend, fix

#34 feat: 빌드파일 수정 및 웹소켓 레이어 수정
  docker-compose.yml
  server/Dockerfile
  server/Pipfile
  server/Pipfile.lock
  server/server/settings.py
Labels: backend, feature

#39 gameroom 페이지 추가 및 레이아웃 구성
  frontend/src/components/Lobby.js
  frontend/src/components/Room.js
  frontend/src/index.js
Labels: frontend, feature

#40 친구 관련 API
  server/friend/__init__.py
  server/friend/apps.py
  server/friend/migrations/0001_initial.py
  server/friend/migrations/__init__.py
  server/friend/models.py
  server/friend/urls.py
  server/friend/views.py
  server/server/settings.py
  server/server/urls.py
Labels: backend, feature

#43 User 모델에 온라인 상태 추가
  server/user/admin.py
  server/user/migrations/0003_user_online_status.py
  server/user/models.py
  server/user/urls.py
  server/user/views.py
Labels: backend, feature

#45 사용자 인증 미들웨어 개선
  server/middleware/auth_middleware.py
  server/server/settings.py
Labels: backend, feature

#47 fetchModule 적용
  frontend/src/components/Lobby.js
  frontend/src/components/Navbar.js
  frontend/src/components/Oauth.js
  frontend/src/utils/fetchmodule.js
Labels: frontend, feature

#46 친구 응답에 온라인 상태 여부 추가
  server/friend/views.py
Labels: backend, feature

#49 🚑 fix: 즉시실행 함수 수정
  frontend/src/components/Lobby.js
Labels: fix

#51 ✨ feat: 플레이어 조인시 번호 할당, 키프레스 psuedo코드 추가, 방 이탈시 disconnect로직 추가
  .gitignore
  server/room/migrations/0004_roomuser_player_number.py
  server/room/migrations/0005_alter_roomuser_unique_together.py
  server/room/models.py
  server/websocket/consumers.py
Labels: backend, feature, chore

#53 🚑 fix: assign_player_number 객체 비교, room, user uuid 참조문제 해결
  server/websocket/consumers.py
Labels: backend, fix

#52 feat: loginStatus 전송, Friend 창 status 표시
  frontend/src/components/Lobby.js
  frontend/src/components/Main.js
  frontend/src/components/MyPage.js
  frontend/src/components/Navbar.js
  frontend/src/components/UserEdit.js
  frontend/src/components/Users.js
  frontend/src/index.js
  frontend/src/utils/loginmodule.js
Labels: frontend, feature

#57 ✨ feat: user ready 기능 추가
  frontend/src/components/Room.js
  server/room/models.py
  server/websocket/consumers.py
Labels: backend, feature

#55 OTP 적용
  server/Pipfile
  server/Pipfile.lock
  server/auth/urls.py
  server/auth/views.py
  server/user/views.py
Labels: backend, feature

#54 ✨ feat: navbar 반응형 추가
  frontend/src/components/Navbar.js
Labels: frontend, feature
